import React, {useState} from 'react'

export default function Order() {
    const[orderID, setOrderID] = useState(""); 
    const [itemID, setItemID] = useState(""); 
    const [buyerID, setBuyerID] = useState("");
    const [sellerID, setSellerID] = useState("");
    const [orderCost, setOrderCost] = useState("");
    const[date, setDate] = useState(""); 
    const[orderStatus, setOrderStatus] = useState(""); 
    const[tracking, setTracking] = useState("");
    const[shippingProvider, setShippingProvider]  = useState(""); 
    const[paymentStatus, setPaymentStatus] = useState(""); 
    
    const submitted = (e) =>{
        e.preventDefault(); 
        console.log(itemID + buyerID + sellerID + orderCost)
    }

    return (
    <div className="form-field">
        <form onSubmit={submitted}>
          <h2>Enter order invoice ID: </h2>
          <label htmlFor="orderID">Order ID: </label>
          <input 
            id="orderID" 
            placeholder="ex. 123456"
            value={orderID}
            onChange={(e) => setOrderID(e.target.value)}/>
          <input className="submit" type="submit" value="Submit"/>
        </form>


        <h2>Edit Order:</h2>
        <form onSubmit={submitted}>
            <label htmlFor="itemID">Item ID: </label>
            <input
                placeholder="Item ID"
                type="text"
                id="itemID"
                name=""
                value={itemID}
                onChange={(e) => setItemID(e.target.value)}
            />
            <label htmlFor="buyerID">Buyer ID: </label>            
            <input
                placeholder="Buyer ID"
                type="text"
                id="buyerID"
                name=""
                value={buyerID}
                onChange={(e) => setBuyerID(e.target.value)}
            />
            <label htmlFor="sellerID">Seller ID: </label>
            <input
                placeholder="Seller ID"
                type="text"
                id=""
                name=""
                value={sellerID}
                onChange={(e) => setSellerID(e.target.value)}
            />
            <label htmlFor="orderCost">Order Cost (USD): </label>
            <input
                placeholder= "Order Cost (USD)"
                type="text"
                id=""
                name=""
                value={orderCost}
                onChange={(e) => setOrderCost(e.target.value)}
            />
            <label htmlFor="orderCost">Order Date (MM/DD/YYYY): </label>
            <input
                placeholder= "01/25/1999"
                type="text"
                id=""
                name=""
                value={date}
                onChange={(e) => setDate(e.target.value)}
            />
            <label htmlFor="shippingProvider">Shipping Provider</label>
            <select
                id="shippingProvider"
                value={shippingProvider}
                onChange={(e)=> setShippingProvider(e.target.value)}
            >
                <option value="Fedex">Fedex</option>
                <option value="USPS">USPS</option>
                <option value="UPS">UPS</option>
            </select>
            <label htmlFor="tracking">Tracking Number: </label>
            <input
                placeholder= "ex. 123456789-98"
                type="text"
                id="tracking"
                name=""
                value={tracking}
                onChange={(e) => setTracking(e.target.value)}
            />
            <label htmlFor="orderStatus">Shipping Status: </label>
                <select
                    id="orderStatus"
                    value={orderStatus}
                    onChange={(e)=> setOrderStatus(e.target.value)}
                >
                    <option value="OrderRecieved">Order Recieved</option>
                    <option value="Shipped">Shipped</option>
                    <option value="Delivered">Delivered</option>
                </select>
            <label htmlFor="paymentStatus">Payment Status: </label>
                <select
                    id="paymentStatus"
                    value={paymentStatus}
                    onChange={(e)=> setPaymentStatus(e.target.value)}
                >
                    <option value="Pending">Pending</option>
                    <option value="Declined">Declined</option>
                    <option value="Paid">Paid</option>
                </select>
            <input className="submit" type="submit" value="Submit"/>
        </form>
    </div>
    )
}

/*
order id //generated by the back end 
item id 
buyer id 
seller id 
order date
order cost 

        <select
          value={productCategory}
          onChange={(e)=> setCategory(e.target.value)}
        >
          <option value="shoes">Shoes</option>
          <option value="hat">Hat</option>
        </select>
*/