import React, {useState} from 'react'

export default function Order() {
    const [itemID, setItemID] = useState(""); 
    const [buyerID, setBuyerID] = useState("");
    const [sellerID, setSellerID] = useState("");
    const [orderCost, setOrderCost] = useState("");
    
    const submitted = (e) =>{
        e.preventDefault(); 
        console.log(itemID + buyerID + sellerID + orderCost)
    }

    return (
    <div className="insert__option">
        <h2>Create New Order</h2>
        <form onSubmit={submitted}>
            <label htmlFor="itemID">Item ID: </label>
            <input
                placeholder="Item ID"
                type="text"
                id="itemID"
                name=""
                value={itemID}
                onChange={(e) => setItemID(e.target.value)}
            />
            <label htmlFor="buyerID">Buyer ID: </label>            
            <input
                placeholder="Buyer ID"
                type="text"
                id=""
                name=""
                value={buyerID}
                onChange={(e) => setBuyerID(e.target.value)}
            />
            <label htmlFor="sellerID">Seller ID: </label>
            <input
                placeholder="Seller ID"
                type="text"
                id=""
                name=""
                value={sellerID}
                onChange={(e) => setSellerID(e.target.value)}
            />
            <label htmlFor="orderCost">Order Cost (USD): </label>
            <input
                placeholder= "Order Cost (USD)"
                type="text"
                id=""
                name=""
                value={orderCost}
                onChange={(e) => setOrderCost(e.target.value)}
            />
            <input className="submit" type="submit" value="Submit"/>
        </form>
    </div>
    )
}

/*
order id //generated by the back end 
item id 
buyer id 
seller id 
order date
order cost 
*/